EXP 9: AIM: Tools for EDA- Study of NumPy Library

NAME: Dhruv Patil

PRN: 25070123146

NumPy:

-Create arrays.

-Perform numerical operations.

In [52]:
# Why NumPy?
## It is faster than lists.
## It is used for numerical computations.
## Base for Pandas

In [53]:
#1. Declaration of NumPy:
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]]) ##ListOfList to print Matrix.
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [54]:
#2. Dimension of Array:
print(a.ndim)
print(b.ndim)

1
2


In [55]:
#3. Printing (rows,coloumns):
print(a.shape)
print(b.shape)

(7,)
(2, 3)


In [56]:
#4. printing datatype: 64bit integer data type
print(a.dtype)
print(b.dtype)

int64
int64


In [57]:
#5. In-Built functions using NumPy
print("Zeros=",np.zeros((2,3)))
print("Ones=",np.ones((2,3)))
print("Identity Matrix=",np.eye((3)))
print("Aranged Array=", np.arange(1,10,2))
print("Equal spaced array=", np.linspace(0,1,4))
print("Mean of a = ", np.mean(a)) #float datatype(64bit)
print("Median of a = ", np.median(a)) #float datatype(64bit)
print("max value of a = ", np.max(a))
print("min value of a = ", np.min(a))
print("sum of a = ", np.sum(a))

Zeros= [[0. 0. 0.]
 [0. 0. 0.]]
Ones= [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Aranged Array= [1 3 5 7 9]
Equal spaced array= [0.         0.33333333 0.66666667 1.        ]
Mean of a =  93.0
Median of a =  30.0
max value of a =  500
min value of a =  1
sum of a =  651


In [58]:
#6. addition and product with a number:
print(a)
print(b)
print(a+5)
print(b*2)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
[  6  15  25  35  45  55 505]
[[ 2  4  6]
 [ 8 10 12]]
